name: Integration Test BDC3

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "*/30 * * * *"


jobs:
  staging__basic_submission:
    if: github.ref != 'refs/heads/prod'
    runs-on: ubuntu-latest
    environment: staging
    env:
      GOOGLE_PROJECT_NAME: firecloud-cgl
      WORKSPACE_NAME: terra-notebook-utils-tests
      GOOGLE_PROJECT_ID: drs-billing-project
      BDCAT_STAGE: staging
      TERRA_DEPLOYMENT_ENV: alpha
      TEST_MULE_CREDS: ${{ secrets.TEST_MULE_CREDS }}
      TERRA_WEBHOOK: ${{ secrets.TERRA_SLACK_WEBHOOK }}
      GEN3_API_KEY: ${{ secrets.GEN3_API_KEY }}
      BDCAT_SB_BROKER_TOKEN: ${{ secrets.BDCAT_SB_BROKER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install -r requirements.txt
      - name: Lint
        run: |
          source environment
          make lint
      - name: Decode credentials
        run: echo -n "${{ secrets.ENCODED_GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d > gcp-creds.json
      # - name: Run basic submission test
      #   run: timeout -s SIGINT 115m ./venv/bin/python -m unittest
      - name: Run basic submission test
        run: |
          timeout -s SIGINT 115m ./venv/bin/python -m test.terra.test_terra
#       - name: Post to Slack
#         run: ./venv/bin/python scripts/post_to_slack.py
      

  staging__version_check:
    if: github.ref != 'refs/heads/prod'
    environment: staging
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT_NAME: firecloud-cgl
      WORKSPACE_NAME: terra-notebook-utils-tests
      GOOGLE_PROJECT_ID: drs-billing-project
      BDCAT_STAGE: staging
      TERRA_DEPLOYMENT_ENV: alpha
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install -r requirements.txt
      - name: Lint
        run: |
          source environment
          make lint
      - name: Decode credentials
        run: echo -n "${{ secrets.ENCODED_GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d > gcp-creds.json
      - name: Run version check test
        run: ./venv/bin/python test/test_version_check.py
#       - name: Post to Slack
#         run: ./venv/bin/python scripts/post_to_slack.py
      

  prod__basic_submission:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    environment: prod
    env:
      GOOGLE_PROJECT_NAME: firecloud-cgl
      WORKSPACE_NAME: terra-notebook-utils-tests
      GOOGLE_PROJECT_ID: drs-billing-project
      BDCAT_STAGE: prod
      TEST_MULE_CREDS: ${{ secrets.TEST_MULE_CREDS }}
      GEN3_API_KEY: ${{ secrets.GEN3_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install -r requirements.txt
      - name: Lint
        run: |
          source environment
          make lint
      - name: Decode credentials
        run: echo "${{ secrets.ENCODED_GOOGLE_APPLICATION_CREDENTIALS }}" > gcp-creds.json
      - name: Run basic submission test
        run: timeout -s SIGINT 115m ./venv/bin/python test/test_basic_submission.py
#       - name: Post to Slack
#         run: ./venv/bin/python scripts/post_to_slack.py
